Requirement already satisfied: numpy in /users/aca22yn/.local/lib/python3.10/site-packages (2.1.2)
Requirement already satisfied: torch in /users/aca22yn/.local/lib/python3.10/site-packages (2.5.0)
Requirement already satisfied: transformers in /users/aca22yn/.local/lib/python3.10/site-packages (4.45.2)
Requirement already satisfied: datasets in /users/aca22yn/.local/lib/python3.10/site-packages (3.0.1)
Requirement already satisfied: accelerate in /users/aca22yn/.local/lib/python3.10/site-packages (1.0.1)
Requirement already satisfied: filelock in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from torch) (3.8.0)
Requirement already satisfied: fsspec in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (2024.6.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (11.6.1.9)
Requirement already satisfied: typing-extensions>=4.8.0 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (4.12.2)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (12.4.127)
Requirement already satisfied: triton==3.1.0 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (3.1.0)
Requirement already satisfied: networkx in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (3.4.1)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (12.4.127)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (10.3.5.147)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (9.1.0.70)
Requirement already satisfied: sympy==1.13.1 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (1.13.1)
Requirement already satisfied: jinja2 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from torch) (3.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (12.3.1.170)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /users/aca22yn/.local/lib/python3.10/site-packages (from torch) (11.2.1.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /users/aca22yn/.local/lib/python3.10/site-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: requests in /users/aca22yn/.local/lib/python3.10/site-packages (from transformers) (2.32.3)
Requirement already satisfied: packaging>=20.0 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from transformers) (21.3)
Requirement already satisfied: regex!=2019.12.17 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from transformers) (2022.10.31)
Requirement already satisfied: safetensors>=0.4.1 in /users/aca22yn/.local/lib/python3.10/site-packages (from transformers) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /users/aca22yn/.local/lib/python3.10/site-packages (from transformers) (4.66.5)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /users/aca22yn/.local/lib/python3.10/site-packages (from transformers) (0.20.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /users/aca22yn/.local/lib/python3.10/site-packages (from transformers) (0.26.0)
Requirement already satisfied: pyyaml>=5.1 in /users/aca22yn/.local/lib/python3.10/site-packages (from transformers) (6.0.2)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /users/aca22yn/.local/lib/python3.10/site-packages (from datasets) (0.3.8)
Requirement already satisfied: pyarrow>=15.0.0 in /users/aca22yn/.local/lib/python3.10/site-packages (from datasets) (17.0.0)
Requirement already satisfied: aiohttp in /users/aca22yn/.local/lib/python3.10/site-packages (from datasets) (3.10.10)
Requirement already satisfied: xxhash in /users/aca22yn/.local/lib/python3.10/site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess in /users/aca22yn/.local/lib/python3.10/site-packages (from datasets) (0.70.16)
Requirement already satisfied: pandas in /users/aca22yn/.local/lib/python3.10/site-packages (from datasets) (2.2.3)
Requirement already satisfied: psutil in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from accelerate) (5.9.4)
Requirement already satisfied: async-timeout<5.0,>=4.0 in /users/aca22yn/.local/lib/python3.10/site-packages (from aiohttp->datasets) (4.0.3)
Requirement already satisfied: attrs>=17.3.0 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from aiohttp->datasets) (22.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /users/aca22yn/.local/lib/python3.10/site-packages (from aiohttp->datasets) (1.4.1)
Requirement already satisfied: aiosignal>=1.1.2 in /users/aca22yn/.local/lib/python3.10/site-packages (from aiohttp->datasets) (1.3.1)
Requirement already satisfied: multidict<7.0,>=4.5 in /users/aca22yn/.local/lib/python3.10/site-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /users/aca22yn/.local/lib/python3.10/site-packages (from aiohttp->datasets) (2.4.3)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /users/aca22yn/.local/lib/python3.10/site-packages (from aiohttp->datasets) (1.15.5)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from packaging>=20.0->transformers) (3.0.9)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from requests->transformers) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from requests->transformers) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from requests->transformers) (2022.9.24)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from requests->transformers) (1.26.12)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from jinja2->torch) (2.1.1)
Requirement already satisfied: pytz>=2020.1 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from pandas->datasets) (2022.6)
Requirement already satisfied: tzdata>=2022.7 in /users/aca22yn/.local/lib/python3.10/site-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: six>=1.5 in /opt/apps/testapps/el7/software/staging/Python/3.10.8-GCCcore-12.2.0/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Requirement already satisfied: propcache>=0.2.0 in /users/aca22yn/.local/lib/python3.10/site-packages (from yarl<2.0,>=1.12.0->aiohttp->datasets) (0.2.0)

[notice] A new release of pip available: 22.3.1 -> 24.2
[notice] To update, run: pip install --upgrade pip
torch 2.5.0
transformers 4.45.2
accelerate 1.0.1
# of gpus:  0
loading llm model meta-llama/Llama-3.2-1B-Instruct
Traceback (most recent call last):
  File "/users/aca22yn/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "/users/aca22yn/.local/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct/resolve/main/config.json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/users/aca22yn/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 403, in cached_file
    resolved_file = hf_hub_download(
  File "/users/aca22yn/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/users/aca22yn/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "/users/aca22yn/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
    _raise_on_head_call_error(head_call_error, force_download, local_files_only)
  File "/users/aca22yn/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1484, in _raise_on_head_call_error
    raise head_call_error
  File "/users/aca22yn/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "/users/aca22yn/.local/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/users/aca22yn/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "/users/aca22yn/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "/users/aca22yn/.local/lib/python3.10/site-packages/huggingface_hub/file_download.py", line 301, in _request_wrapper
    hf_raise_for_status(response)
  File "/users/aca22yn/.local/lib/python3.10/site-packages/huggingface_hub/utils/_http.py", line 423, in hf_raise_for_status
    raise _format(GatedRepoError, message, response) from e
huggingface_hub.errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-67164173-79aa25ee5af545d262a5e8e3;7c59cf25-de56-4a1b-aa61-876798defc1b)

Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-1B-Instruct is restricted. You must have access to it and be authenticated to access it. Please log in.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/parscratch/users/aca22yn/wanda/main.py", line 110, in <module>
    main()
  File "/mnt/parscratch/users/aca22yn/wanda/main.py", line 57, in main
    model = get_llm(args.model, args.cache_dir)
  File "/mnt/parscratch/users/aca22yn/wanda/main.py", line 17, in get_llm
    model = AutoModelForCausalLM.from_pretrained(
  File "/users/aca22yn/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 526, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/users/aca22yn/.local/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1006, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/users/aca22yn/.local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 570, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/users/aca22yn/.local/lib/python3.10/site-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "/users/aca22yn/.local/lib/python3.10/site-packages/transformers/utils/hub.py", line 421, in cached_file
    raise EnvironmentError(
OSError: You are trying to access a gated repo.
Make sure to have access to it at https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct.
401 Client Error. (Request ID: Root=1-67164173-79aa25ee5af545d262a5e8e3;7c59cf25-de56-4a1b-aa61-876798defc1b)

Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-3.2-1B-Instruct/resolve/main/config.json.
Access to model meta-llama/Llama-3.2-1B-Instruct is restricted. You must have access to it and be authenticated to access it. Please log in.
